CREATE TABLE shipping_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    label VARCHAR(40) NOT NULL,
    recipient_name VARCHAR(80) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    address1 VARCHAR(255) NOT NULL,
    address2 VARCHAR(255) NOT NULL DEFAULT '',
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX shipping_addresses_user_id_idx
    ON shipping_addresses (user_id, is_default DESC, id ASC);
