ALTER TABLE admin_display_settings
ADD COLUMN hero_cta_label VARCHAR(80) NOT NULL DEFAULT '컬렉션 보기',
ADD COLUMN hero_cta_href VARCHAR(255) NOT NULL DEFAULT '/search';

ALTER TABLE categories
ADD COLUMN display_order INTEGER NOT NULL DEFAULT 0,
ADD COLUMN is_visible BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN cover_image_url VARCHAR(255) NOT NULL DEFAULT '/images/products/living-01.jpg',
ADD COLUMN cover_image_alt VARCHAR(255) NOT NULL DEFAULT '카테고리 커버 이미지',
ADD COLUMN hero_title VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN hero_subtitle TEXT NOT NULL DEFAULT '';

UPDATE categories
SET
    display_order = CASE slug
        WHEN 'living' THEN 10
        WHEN 'kitchen' THEN 20
        WHEN 'wellness' THEN 30
        ELSE 100
    END,
    cover_image_url = CASE slug
        WHEN 'living' THEN '/images/products/living-01.jpg'
        WHEN 'kitchen' THEN '/images/products/kitchen-01.jpg'
        WHEN 'wellness' THEN '/images/products/wellness-01.jpg'
        ELSE '/images/products/living-01.jpg'
    END,
    cover_image_alt = CASE slug
        WHEN 'living' THEN '리빙 카테고리 커버'
        WHEN 'kitchen' THEN '키친 카테고리 커버'
        WHEN 'wellness' THEN '웰니스 카테고리 커버'
        ELSE '카테고리 커버 이미지'
    END,
    hero_title = CASE slug
        WHEN 'living' THEN '공간을 정리하는 리빙 셀렉션'
        WHEN 'kitchen' THEN '테이블과 조리를 위한 키친 셀렉션'
        WHEN 'wellness' THEN '호흡과 루틴을 위한 웰니스 셀렉션'
        ELSE name
    END,
    hero_subtitle = CASE slug
        WHEN 'living' THEN '소재와 질감이 살아 있는 정리, 침실, 거실 아이템을 차분하게 둘러보세요.'
        WHEN 'kitchen' THEN '플레이팅과 조리 동선에 맞춘 실용적인 도구와 식기를 한 번에 살펴보세요.'
        WHEN 'wellness' THEN '쉬는 시간과 셀프 케어 루틴에 자연스럽게 섞이는 웰니스 아이템을 모았습니다.'
        ELSE description
    END;

CREATE INDEX categories_display_order_idx
ON categories (is_visible DESC, display_order ASC, id ASC);

CREATE TABLE display_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    subtitle TEXT NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE display_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT NOT NULL REFERENCES display_sections (id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    subtitle TEXT NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    image_alt VARCHAR(255) NOT NULL,
    href VARCHAR(255) NOT NULL,
    cta_label VARCHAR(80) NOT NULL,
    accent_color VARCHAR(20) NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    starts_at TIMESTAMP WITH TIME ZONE NULL,
    ends_at TIMESTAMP WITH TIME ZONE NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX display_sections_order_idx
ON display_sections (display_order ASC, id ASC);

CREATE INDEX display_items_section_order_idx
ON display_items (section_id, is_visible DESC, display_order ASC, id ASC);

INSERT INTO display_sections (code, title, subtitle, display_order, is_visible, updated_at)
VALUES
    ('HERO', '시즌 대표 배너', '메인 비주얼과 CTA를 함께 노출합니다.', 10, TRUE, NOW()),
    ('FEATURED_CATEGORY', '카테고리 셀렉션', '운영 중인 주요 카테고리를 전면에서 소개합니다.', 20, TRUE, NOW()),
    ('CURATED_PICK', '큐레이션 픽', '지금 보여주고 싶은 추천 상품을 강조합니다.', 30, TRUE, NOW()),
    ('NEW_ARRIVALS', '신상품 드롭', '최근 등록된 상품을 우선 노출합니다.', 40, TRUE, NOW()),
    ('BEST_SELLERS', '베스트셀러', '인기 점수가 높은 상품을 중심으로 구성합니다.', 50, TRUE, NOW()),
    ('PROMOTION', '프로모션 배너', '기획전과 프로모션 링크를 하단 섹션에 노출합니다.', 60, TRUE, NOW());

INSERT INTO display_items (
    section_id,
    title,
    subtitle,
    image_url,
    image_alt,
    href,
    cta_label,
    accent_color,
    display_order,
    is_visible,
    starts_at,
    ends_at,
    updated_at
)
VALUES
    (
        (SELECT id FROM display_sections WHERE code = 'HERO'),
        '리빙 봄 에디션',
        '침실과 거실의 톤을 한 번에 정리하는 시즌 셀렉션',
        '/images/products/living-01.jpg',
        '리빙 봄 에디션 배너',
        '/category/living',
        '리빙 보기',
        '#D6512D',
        10,
        TRUE,
        NULL,
        NULL,
        NOW()
    ),
    (
        (SELECT id FROM display_sections WHERE code = 'PROMOTION'),
        '키친 테이블웨어 위크',
        '식기와 플레이팅 제품을 한데 모아보는 프로모션',
        '/images/products/kitchen-02.jpg',
        '키친 테이블웨어 프로모션 배너',
        '/category/kitchen',
        '키친 보기',
        '#D98D32',
        10,
        TRUE,
        NULL,
        NULL,
        NOW()
    ),
    (
        (SELECT id FROM display_sections WHERE code = 'PROMOTION'),
        '웰니스 루틴 큐레이션',
        '휴식과 셀프 케어 루틴에 어울리는 아이템 제안',
        '/images/products/wellness-02.jpg',
        '웰니스 프로모션 배너',
        '/category/wellness',
        '웰니스 보기',
        '#2D7E67',
        20,
        TRUE,
        NULL,
        NULL,
        NOW()
    );
