ALTER TABLE users
ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
ADD COLUMN phone VARCHAR(30),
ADD COLUMN last_login_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN marketing_opt_in BOOLEAN NOT NULL DEFAULT FALSE;
