CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(80) NOT NULL,
    description VARCHAR(255) NOT NULL,
    accent_color VARCHAR(20) NOT NULL
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL REFERENCES categories (id),
    slug VARCHAR(120) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    summary VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    price NUMERIC(12, 0) NOT NULL,
    badge VARCHAR(50) NOT NULL,
    accent_color VARCHAR(20) NOT NULL,
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    stock INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE customer_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(30) NOT NULL UNIQUE,
    customer_name VARCHAR(80) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    address1 VARCHAR(255) NOT NULL,
    address2 VARCHAR(255) NOT NULL,
    note VARCHAR(255) NOT NULL,
    subtotal NUMERIC(12, 0) NOT NULL,
    shipping_fee NUMERIC(12, 0) NOT NULL,
    total NUMERIC(12, 0) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE customer_order_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES customer_orders (id),
    product_id BIGINT NOT NULL,
    product_name VARCHAR(120) NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(12, 0) NOT NULL,
    line_total NUMERIC(12, 0) NOT NULL
);

INSERT INTO categories (slug, name, description, accent_color) VALUES
('living', '리빙', '공간을 차분하게 정리하는 데일리 리빙 셀렉션', '#ff8d6b'),
('kitchen', '키친', '조리와 플레이팅의 리듬을 바꾸는 키친 라인', '#ffbf5f'),
('wellness', '웰니스', '하루의 템포를 조절하는 셀프 케어 제품', '#68b78e');

INSERT INTO products (category_id, slug, name, summary, description, price, badge, accent_color, featured, stock) VALUES
((SELECT id FROM categories WHERE slug = 'living'), 'linen-bed-set', '린넨 베드 세트', '내추럴 무드로 침실 톤을 정리하는 베스트 조합', '크림, 스톤, 세이지 세 가지 톤으로 구성한 침구 세트입니다. 촉감이 가볍고 계절감이 길어서 MVP 대표 상품으로 잡기 좋습니다.', 89000, 'BEST', '#ff8d6b', TRUE, 24),
((SELECT id FROM categories WHERE slug = 'living'), 'curve-floor-lamp', '커브 플로어 램프', '공간의 분위기를 한 번에 잡아주는 곡선형 무드 조명', '소파 옆에 두기 좋은 높이와 부드러운 광량을 가진 플로어 램프입니다. 상세 페이지 레이아웃 검증용으로도 적합합니다.', 129000, 'NEW', '#f68a7c', TRUE, 11),
((SELECT id FROM categories WHERE slug = 'kitchen'), 'stone-plate-set', '스톤 플레이트 4P', '플레이팅 사진이 잘 나오는 매트 텍스처 플레이트', '브런치, 디저트, 간단한 메인 요리에 모두 어울리는 플레이트 세트입니다. 리스트와 상세 화면의 가격 영역을 테스트하기 좋은 상품입니다.', 42000, 'LIMITED', '#ffbf5f', TRUE, 36),
((SELECT id FROM categories WHERE slug = 'kitchen'), 'brew-mug', '브루 머그', '아침 루틴에 맞춘 420ml 세라믹 머그', '손에 안정적으로 잡히는 곡선 손잡이와 두께감이 특징입니다. 웨어러블한 데일리 키친 상품군으로 분류했습니다.', 18000, 'DAILY', '#d79a41', FALSE, 54),
((SELECT id FROM categories WHERE slug = 'wellness'), 'calm-aroma-oil', '캄 아로마 오일', '저녁 루틴에 어울리는 우디 플로럴 블렌드', '호흡을 늦추고 집중을 정리하는 데 초점을 둔 아로마 오일입니다. 상세 설명과 정책 콘텐츠 검증용 웰니스 상품입니다.', 26000, 'PICK', '#68b78e', TRUE, 48),
((SELECT id FROM categories WHERE slug = 'wellness'), 'soft-robe', '소프트 로브', '샤워 후 바로 입기 좋은 라이트 코튼 로브', '집 안에서 편하게 입을 수 있는 미니멀 로브입니다. 웰니스 카테고리의 서브 대표 상품으로 배치합니다.', 59000, 'REST', '#4e9f79', FALSE, 19);

