ALTER TABLE customer_orders
ALTER COLUMN order_number TYPE VARCHAR(40);

DROP INDEX IF EXISTS customer_orders_phone_created_at_idx;

ALTER TABLE products
ADD CONSTRAINT products_stock_nonnegative CHECK (stock >= 0);

CREATE TABLE guest_order_access_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES customer_orders (id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_used_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX guest_order_access_tokens_order_expiry_idx
ON guest_order_access_tokens (order_id, expires_at);

CREATE TABLE guest_order_access_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(20) NOT NULL,
    order_number VARCHAR(40) NOT NULL,
    request_key_hash VARCHAR(64) NOT NULL,
    succeeded BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX guest_order_access_audit_rate_limit_idx
ON guest_order_access_audit_logs (action, request_key_hash, succeeded, created_at);
