CREATE TABLE shopping_cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_token VARCHAR(64) NOT NULL,
    product_id BIGINT NOT NULL REFERENCES products (id),
    quantity INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT shopping_cart_items_session_product_uk UNIQUE (session_token, product_id)
);

CREATE INDEX shopping_cart_items_session_token_idx ON shopping_cart_items (session_token);
