UPDATE customer_orders
SET status = 'PAID'
WHERE status = 'RECEIVED';

CREATE TABLE order_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE REFERENCES customer_orders (id),
    payment_method VARCHAR(30) NOT NULL,
    payment_status VARCHAR(30) NOT NULL,
    provider_code VARCHAR(40) NOT NULL,
    reference_code VARCHAR(80) NOT NULL UNIQUE,
    message VARCHAR(255) NOT NULL,
    approved_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

INSERT INTO order_payments (
    order_id,
    payment_method,
    payment_status,
    provider_code,
    reference_code,
    message,
    approved_at,
    created_at,
    updated_at
)
SELECT
    customer_orders.id,
    'CARD',
    CASE customer_orders.status
        WHEN 'PENDING_PAYMENT' THEN 'PENDING'
        WHEN 'REFUNDED' THEN 'REFUNDED'
        WHEN 'CANCELLED' THEN 'CANCELLED'
        ELSE 'SUCCEEDED'
    END,
    'LEGACY_IMPORT',
    'LEGACY-' || customer_orders.order_number,
    '기존 주문 데이터에서 이전된 결제 정보입니다.',
    CASE
        WHEN customer_orders.status IN ('PAID', 'REFUNDED', 'DELIVERED', 'SHIPPED', 'PREPARING')
            THEN customer_orders.created_at
        ELSE NULL
    END,
    customer_orders.created_at,
    customer_orders.created_at
FROM customer_orders
WHERE NOT EXISTS (
    SELECT 1
    FROM order_payments
    WHERE order_payments.order_id = customer_orders.id
);
